### ISSUE TITLE
base stats dont show up

### ISSUE THREAD

**Issue by hullo2021** [rowin1/Pokemon-Showdown-Enhanced-Tooltips#33]
hey there, great extension. the previous issue of the display not coming up for your pokemon has been fixed. however, the base stats do not show up for either side with the option selected in the extension. thanks.

**Comment by generiskk** [comment]
Addon has not been updated on the chrome store, however my fix has been pushed to both Firefox and Chrome store.

[Chrome](https://chrome.google.com/webstore/detail/pok%C3%A9mon-showdown-enhanced/aggbolenhnpdhgcfpknifdiheppbmblb)

[Firefox](https://addons.mozilla.org/en-US/firefox/addon/psim-enhanced-tooltips/)

**Comment by ciesling** [comment]
Thanks a lot!

**Comment by hullo2021** [comment]
> Addon has not been updated on the chrome store, however my fix has been pushed to both Firefox and Chrome store.
> 
> [Chrome](https://chrome.google.com/webstore/detail/pok%C3%A9mon-showdown-enhanced/aggbolenhnpdhgcfpknifdiheppbmblb)
> 
> [Firefox](https://addons.mozilla.org/en-US/firefox/addon/psim-enhanced-tooltips/)

Thanks for the fix gene appreciate it. I downloaded your extension update however the base stats still do not work on chrome. Haven't tried firefox. will check it

**Comment by generiskk** [comment]
hmm, I will check it up, will post in this issue when I know more.

**Comment by hullo2021** [comment]
Thanks, you're the best.

**Comment by generiskk** [comment]
I seem to have located the issue, seems to be related to how the addon checks local storage for the "showBaseStats" key. -  However I am not the most experienced JavaScript developer, so it might take a little while to fix this. 

However, here is a version of the extension with the base stats forced to show. 

[Chrome version](https://github.com/rowin1/Pokemon-Showdown-Enhanced-Tooltips/files/6411394/chrome.zip) - Just extract the zip to somewhere, and go to `chrome://extensions/`, enable dev mode in top right corner, then load unpacked.

[Firefox version](https://github.com/rowin1/Pokemon-Showdown-Enhanced-Tooltips/files/6411395/firefox.zip) - I sadly haven't been able to test in Firefox for this, however it should work as the chrome version. - [You need to disable signature checking for this to work](https://stackoverflow.com/questions/31952727/how-can-i-disable-signature-checking-for-firefox-add-ons)

![image](https://user-images.githubusercontent.com/36735685/116814083-47cc2e00-ab57-11eb-809c-b094cf33f8a3.png)

**Comment by hullo2021** [comment]
Thank you generiskk. it's showing up now.  brilliant work.

**Comment by hullo2021** [comment]
> I seem to have located the issue, seems to be related to how the addon checks local storage for the "showBaseStats" key. - However I am not the most experienced JavaScript developer, so it might take a little while to fix this.
> 
> However, here is a version of the extension with the base stats forced to show.
> 
> [Chrome version](https://github.com/rowin1/Pokemon-Showdown-Enhanced-Tooltips/files/6411394/chrome.zip) - Just extract the zip to somewhere, and go to `chrome://extensions/`, enable dev mode in top right corner, then load unpacked.
> 
> [Firefox version](https://github.com/rowin1/Pokemon-Showdown-Enhanced-Tooltips/files/6411395/firefox.zip) - I sadly haven't been able to test in Firefox for this, however it should work as the chrome version. - [You need to disable signature checking for this to work](https://stackoverflow.com/questions/31952727/how-can-i-disable-signature-checking-for-firefox-add-ons)
> 
> ![image](https://user-images.githubusercontent.com/36735685/116814083-47cc2e00-ab57-11eb-809c-b094cf33f8a3.png)

Thank you generiskk. it's showing up now. brilliant work.
